### ISSUE TITLE
PluginManager - node_modules directory not found

### ISSUE THREAD

**Issue by stefanwerfling** [stefanwerfling/flyingfish#63]
```
{
"date":"Thu Feb 29 2024 07:43:20 GMT+0000 (Coordinated Universal Time)",
"error":{},"exception":true,"level":"error","message":"uncaughtException: node_modules directory not found: /opt/flyingfish/node_modules
Error: node_modules directory not found: /opt/flyingfish/node_modules
    at PluginManager.scan (file:///opt/flyingfish/core/dist/src/inc/PluginSystem/PluginManager.js:36:19)
    at PluginManager.start (file:///opt/flyingfish/core/dist/src/inc/PluginSystem/PluginManager.js:27:34)
    at file:///opt/flyingfish/backend/dist/main.js:77:14","os":{"loadavg":[4.55,2.17,0.85],"uptime":26813.75},"process":{"argv":[
"/usr/local/bin/node",
"/opt/flyingfish/backend/dist/main.js","--envargs=1"
],
"cwd":"/opt/flyingfish",
"execPath":"/usr/local/bin/node",
"gid":0,"memoryUsage": {
"arrayBuffers":918216,
"external":5666492,
"heapTotal":54632448,
"heapUsed":44404312,
"rss":111673344
},
"pid":1,
"uid":0,
"version":"v18.19.1"
},
"stack":"Error: node_modules directory not found: /opt/flyingfish/node_modules
    at PluginManager.scan (file:///opt/flyingfish/core/dist/src/inc/PluginSystem/PluginManager.js:36:19)
    at PluginManager.start (file:///opt/flyingfish/core/dist/src/inc/PluginSystem/PluginManager.js:27:34)
    at file:///opt/flyingfish/backend/dist/main.js:77:14",
"timestamp":"2024-02-29T07:43:20.522Z",
"trace":[{"column":19,"file":"file:///opt/flyingfish/core/dist/src/inc/PluginSystem/PluginManager.js","function":"PluginManager.scan","line":36,"method":"scan","native":false},{"column":34,"file":"file:///opt/flyingfish/core/dist/src/inc/PluginSystem/PluginManager.js","function":"PluginManager.start","line":27,"method":"start","native":false},{"column":14,"file":"file:///opt/flyingfish/backend/dist/main.js","function":null,"line":77,"method":null,"native":false}]
}
```

**Comment by stefanwerfling** [comment]
{"level":"error","message":"The plugin manager could not load the plugins. node_modules directory not found: /opt/flyingfish/node_modules/backend","stack":"Error: node_modules directory not found: /opt/flyingfish/node_modules/backend
    at PluginManager.scan (file:///opt/flyingfish/core/dist/src/inc/PluginSystem/PluginManager.js:38:23)
    at PluginManager.start (file:///opt/flyingfish/core/dist/src/inc/PluginSystem/PluginManager.js:27:34)
    at file:///opt/flyingfish/backend/dist/main.js:78:18","timestamp":"2024-02-29T14:29:53.833Z"}
{
"level":"error",
"message":"Error while connecting to the database Mysql package has not been found installed. Try to install it: npm install mysql --save","stack":"DriverPackageNotInstalledError: Mysql package has not been found installed. Try to install it: npm install mysql --save\n    at MysqlDriver.loadDependencies (/opt/flyingfish/core/node_modules/typeorm/driver/mysql/MysqlDriver.js:965:23)
    at new MysqlDriver (/opt/flyingfish/core/node_modules/typeorm/driver/mysql/MysqlDriver.js:275:14)
    at DriverFactory.create (/opt/flyingfish/core/node_modules/typeorm/driver/DriverFactory.js:34:24)
    at new DataSource (/opt/flyingfish/core/node_modules/typeorm/data-source/DataSource.js:53:59)
    at DBHelper.init (file:///opt/flyingfish/core/dist/src/inc/Db/MariaDb/DBHelper.js:5:28)
    at file:///opt/flyingfish/backend/dist/main.js:85:24","timestamp":"2024-02-29T14:29:53.847Z"}
