### ISSUE TITLE
Broken CLI Pipe for Docker image build

### ISSUE THREAD

**Issue by stefanwerfling** [stefanwerfling/flyingfish#64]
As someone may have already noticed, there is a [bug in the PluginManager ](https://github.com/stefanwerfling/flyingfish/issues/63)in image v1.1.1. When I wanted to fix this with a new version, the build process of the Docker image no longer worked.

NPM keeps failing when installing dependencies on ARM64.

I'm still analyzing why. I currently wanted to address the problem with my own packet management. However, the problem increasingly seems to be due to the version stored in the ARM64 Basic image of nodejs18.

Please reinstall version v1.0.23 first in order to be able to use a working version of Flyingfish.

I'll keep you updated.

```
#169 864.8 npm http fetch GET 200 ***@jridgewell%2fgen-mapping 372ms (cache miss)
#169 865.4 npm http fetch GET 200 ***@jridgewell%2fset-array 303ms (cache miss)
#169 878.1 npm verb reify failed optional dependency /opt/flyingfish/node_modules/glob-watcher/node_modules/fsevents
#169 878.1 npm verb reify failed optional dependency /opt/flyingfish/node_modules/bindings
#169 878.1 npm verb reify failed optional dependency /opt/flyingfish/node_modules/nan
#169 878.1 npm verb reify failed optional dependency /opt/flyingfish/node_modules/file-uri-to-path
#169 878.3 npm verb reify failed optional dependency /opt/flyingfish/node_modules/fsevents
#169 882.6 npm http fetch POST 401 ***-/npm/v1/security/advisories/bulk 9285ms
#169 910.5 npm http fetch POST 400 ***-/npm/v1/security/audits/quick 1992ms
#169 910.8 npm verb audit error HttpErrorGeneral: 400 Bad Request - POST ***-/npm/v1/security/audits/quick
#169 910.8 npm verb audit error     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
#169 910.8 npm verb audit error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
#169 910.8 npm verb audit error     at async [getReport] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:335:21)
#169 910.8 npm verb audit error     at async AuditReport.run (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:106:19)
#169 910.8 npm verb audit error  HttpErrorGeneral: 400 Bad Request - POST ***-/npm/v1/security/audits/quick
#169 910.8 npm verb audit error     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
#169 910.8 npm verb audit error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
#169 910.8 npm verb audit error     at async [getReport] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:335:21)
#169 910.8 npm verb audit error     at async AuditReport.run (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:106:19) {
#169 910.8 npm verb audit error   headers: [Object: null prototype] {
#169 910.8 npm verb audit error     server: [ 'nginx' ],
#169 910.8 npm verb audit error     date: [ 'Tue, 05 Mar 2024 23:13:10 GMT' ],
#169 910.8 npm verb audit error     'content-type': [ 'application/json' ],
#169 910.8 npm verb audit error     'content-length': [ '228' ],
#169 910.8 npm verb audit error     connection: [ 'keep-alive' ],
#169 910.8 npm verb audit error     'x-content-type-options': [ 'nosniff' ],
#169 910.8 npm verb audit error     'content-security-policy': [
#169 910.8 npm verb audit error       'sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation'
#169 910.8 npm verb audit error     ],
#169 910.8 npm verb audit error     'x-xss-protection': [ '1; mode=block' ],
#169 910.8 npm verb audit error     'x-fetch-attempts': [ '1' ]
#169 910.8 npm verb audit error   },
#169 910.8 npm verb audit error   statusCode: 400,
#169 910.8 npm verb audit error   code: 'E400',
#169 910.8 npm verb audit error   method: 'POST',
#169 910.8 npm verb audit error   uri: '***-/npm/v1/security/audits/quick',
#169 910.8 npm verb audit error   body: <Buffer 0a 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d 3d ... 178 more bytes>,
#169 910.8 npm verb audit error   pkgid: 'quick'
#169 910.8 npm verb audit error }
#169 1160.1 npm verb reify failed optional dependency /opt/flyingfish/node_modules/hawk
#169 1160.1 npm verb reify failed optional dependency /opt/flyingfish/node_modules/hoek
#169 1160.1 npm verb reify failed optional dependency /opt/flyingfish/node_modules/boom
#169 1160.1 npm verb reify failed optional dependency /opt/flyingfish/node_modules/cryptiles
#169 1160.1 npm verb reify failed optional dependency /opt/flyingfish/node_modules/sntp
#169 1160.4 npm verb reify failed optional dependency /opt/flyingfish/node_modules/file-uri-to-path
#169 1160.5 npm verb reify failed optional dependency /opt/flyingfish/node_modules/bindings
#169 1160.5 npm verb reify failed optional dependency /opt/flyingfish/node_modules/glob-watcher/node_modules/fsevents
#169 1160.5 npm verb reify failed optional dependency /opt/flyingfish/node_modules/nan
#169 1339.0 npm notice 
#169 1339.0 npm notice New minor version of npm available! 10.2.4 -> 10.5.0
#169 1339.0 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.5.0>
#169 1339.0 npm notice Run `npm install -g npm@10.5.0` to update!
#169 1339.0 npm notice 
#169 1339.2 npm verb stack Error: Client network socket disconnected before secure TLS connection was established
#169 1339.2 npm verb stack     at connResetException (node:internal/errors:720:14)
#169 1339.2 npm verb stack     at TLSSocket.onConnectEnd (node:_tls_wrap:1714:19)
#169 1339.2 npm verb stack     at TLSSocket.emit (node:events:529:35)
#169 1339.2 npm verb stack     at endReadableNT (node:internal/streams/readable:1400:12)
#169 1339.2 npm verb stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
#169 1339.2 npm verb cwd /opt/flyingfish
#169 1339.2 npm verb Linux 6.5.0-1015-azure
#169 1339.2 npm verb node v18.19.1
#169 1339.2 npm verb npm  v10.2.4
#169 1339.2 npm ERR! code ECONNRESET
#169 1339.7 npm ERR! network Client network socket disconnected before secure TLS connection was established
#169 1339.7 npm ERR! network This is a problem related to network connectivity.
#169 1339.7 npm ERR! network In most cases you are behind a proxy or have bad network settings.
#169 1339.7 npm ERR! network 
#169 1339.7 npm ERR! network If you are behind a proxy, please make sure that the
#169 1339.7 npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
#169 1339.7 npm verb exit 1
```

**Comment by stefanwerfling** [comment]
Fixed:
https://github.com/stefanwerfling/flyingfish/commit/ca2499a01507bbfbcbe76cebb046dc6d173790d6
https://github.com/stefanwerfling/flyingfish/commit/c80cbd5d556f8a2ab8badd526b80a12bf3b3c4c0
https://github.com/stefanwerfling/flyingfish/commit/fe7a95ef1f0a87c2a05d129219eed6aa8905a505
